# small_script_to_read_npy.py
import numpy as np

print("--- Reading python_mel_for_speaker_encoder.npy ---")
mel_data = np.load("python_mel_for_speaker_encoder.npy") # Ensure this .npy was generated by the LATEST python script
print(f"Python Mel Shape for Speaker Encoder: {mel_data.shape}") 
print(f"Python Mel Length: {mel_data.size}")
print("Python Mel Data (first 50 flat, F8 format):")
for i, val in enumerate(mel_data.flatten()[:50]):
    print(f"{val:.8f}", end=", ")
    if (i + 1) % 10 == 0: print("") # Newline every 10 for readability
print("\n")

if mel_data.size > 1000:
    print("Python Mel Data (middle 10 flat around index 500, F8 format):")
    for i, val in enumerate(mel_data.flatten()[500:510]):
        print(f"{val:.8f}", end=", ")
    print("\n") 